In [1]:
import numpy as np

In [ ]:
# как создать матрицу?

In [ ]:
# как двумерный массив Numpy
np.array( [ [1,1] , [2,3] , [4,5] ] )

In [2]:
# преобразовать из Pandas DataFrame
import pandas as pd

data=[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]
df = pd.DataFrame(data)

A = df.values

print('Data Frame:')
print(df)
print('Matrix:')
print(A)

Data Frame:
    0   1   2
0   1   2   3
1   4   5   6
2   7   8   9
3  10  11  12
Matrix:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [ ]:
# размер матрицы
np.shape(A)

In [ ]:
# вектор-столбец
x=np.array([1,2,3])
np.reshape(x,(3,1))

In [ ]:
# вектор-строка
np.reshape(x,(1,3))

In [ ]:
# вектор-строка
x_row=np.array([1, 2, 3], ndmin=2)
print(x_row,np.shape(x_row))

In [ ]:
# индексация матриц (двумерных массивов numpy)
print('матрица А:')
print(A)
print('Первая строка матрицы А:')
print(A[0])
print('Третий столбец матрицы А:')
print(A[:,2])
print('Элемент а_43:')
print(A[3,2])

In [ ]:
# создание специальных матриц

In [ ]:
# нулевая
np.zeros((2,3))

In [ ]:
# единичная
np.eye(3)

In [ ]:
# матрица единиц
np.ones((3,5))

In [ ]:
# Диагональная
diagonal=[1,2,3]
np.diag(diagonal)

In [ ]:
# Шаровая
5*np.eye(3)

In [ ]:
A=np.array([[1,1],[2,3],[4,5]])
B=np.array([[1,-1],[-2,3],[4,-5]])

In [ ]:
A

In [ ]:
B

In [ ]:
A+B

In [ ]:
B+A

In [ ]:
A-B

In [ ]:
2*A

In [ ]:
A.T

In [17]:
# как транспонировать вектор?
x=np.array([1,2,3])
print(np.shape(x))
x.T
print(np.shape(x.T))

(3,)
(3,)


In [15]:
x_col=np.reshape(x,(3,1))
print(x_col)
print(np.shape(x_col))

[[1]
 [2]
 [3]]
(3, 1)


In [18]:
x_col.T

array([[1, 2, 3]])

In [ ]:
print(np.shape(x))
print(np.shape(x_col))
print(np.shape(x_col.T))

In [3]:
import numpy as np

Husband_Income = np.array([100,220,140])
Wife_Income = np.array([150,200,130])
Mother_In_Law_Income = np.array([90,80,100])

Husband_Consumption = np.array([50,50,60])
Wife_Consumption = np.array([100,80,140])
Mother_In_Law_Consumption = np.array([100,20,140])

In [9]:
income_matrix = np.array([Husband_Income, Wife_Income, Mother_In_Law_Income])
income_matrix = income_matrix.T
income_matrix

array([[100, 150,  90],
       [220, 200,  80],
       [140, 130, 100]])

In [11]:
consumption_matrix = np.array([Husband_Consumption, Wife_Consumption, Mother_In_Law_Consumption]).T
consumption_matrix

array([[ 50, 100, 100],
       [ 50,  80,  20],
       [ 60, 140, 140]])

In [12]:
income_matrix = income_matrix * 0.87
income_matrix

array([[ 87. , 130.5,  78.3],
       [191.4, 174. ,  69.6],
       [121.8, 113.1,  87. ]])

In [13]:
balance = income_matrix - consumption_matrix
balance

array([[ 37. ,  30.5, -21.7],
       [141.4,  94. ,  49.6],
       [ 61.8, -26.9, -53. ]])